-- Generated by hypr2lua-web.

local activeBorderColor = "rgb(36a166)"
local inactiveBorderColor = "rgb(302f27)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    border_size = 2,
    gaps_in = 4,
    gaps_out = 8,
  },
  group = {
    col = {
      border_active = activeBorderColor,
    },
  },
  animations = {
    enabled = true,
  },
  decoration = {
    shadow = {
      enabled = true,
      range = 12,
      render_power = 4,
      offset = "0 2",
    },
    active_opacity = 0.98,
    inactive_opacity = 0.94,
    fullscreen_opacity = 1.0,
  },
})

hl.curve("water", { type = "bezier", points = { { 0.22, 0.85 }, { 0.30, 1 } } })

hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 5,
  bezier = "water",
})
hl.animation({
  leaf = "windowsIn",
  enabled = true,
  speed = 5,
  bezier = "water",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 4,
  bezier = "water",
})
hl.animation({
  leaf = "windowsMove",
  enabled = true,
  speed = 5,
  bezier = "water",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 4,
  bezier = "water",
})
hl.animation({
  leaf = "fadeIn",
  enabled = true,
  speed = 4,
  bezier = "water",
})
hl.animation({
  leaf = "fadeOut",
  enabled = true,
  speed = 3,
  bezier = "water",
})
hl.animation({
  leaf = "layers",
  enabled = true,
  speed = 4,
  bezier = "water",
})
hl.animation({
  leaf = "layersIn",
  enabled = true,
  speed = 4,
  bezier = "water",
})
hl.animation({
  leaf = "layersOut",
  enabled = true,
  speed = 3,
  bezier = "water",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 5,
  bezier = "water",
})

hl.layer_rule({
  blur = true,
  match = {
    namespace = "walker",
  },
})
hl.layer_rule({
  ignore_alpha = 0,
  match = {
    namespace = "walker",
  },
})
hl.layer_rule({
  blur = true,
  match = {
    namespace = "waybar",
  },
})
hl.layer_rule({
  blur = true,
  match = {
    namespace = "notifications",
  },
})
hl.layer_rule({
  ignore_alpha = 0,
  match = {
    namespace = "notifications",
  },
})
hl.layer_rule({
  blur = true,
  match = {
    namespace = "vicinae",
  },
})
hl.layer_rule({
  blur = true,
  match = {
    namespace = "swayosd",
  },
})
hl.layer_rule({
  ignore_alpha = 0.1,
  match = {
    namespace = "waybar",
  },
})
hl.layer_rule({
  ignore_alpha = 0.1,
  match = {
    namespace = "vicinae",
  },
})
