[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\r/home/eyeriis)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x5\xa6\0\0\0\x30\0\0\v8\0\0\a\0\0\0\x5\xa6\0\0\0\x30\0\0\v8\0\0\a\0\0\0\0\0\0\0\0\0\v@\0\0\x5\xa6\0\0\0\x30\0\0\v8\0\0\a\0)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(600 0)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/eyeriis/Videos/movie/movie.iso, file:///home/eyeriis/Videos/movie/movies/movie_0.mpg, file:///home/eyeriis/Videos/movie/dvd_tree/VIDEO_TS/VTS_01_0.VOB, file:///home/eyeriis/Videos/movie/dvd_tree/VIDEO_TS/, file:///home/eyeriis/Videos/movie/dvd_tree/VIDEO_TS/VIDEO_TS.VOB, file:///var/tmp/movie_preview.mpg
times=0, 20385, 0, 0, 0, 5980
